language: en

recipe: default_v1
assistant_id: 20240207-133419-grim-system
pipeline: null
policies: null

#pipeline:
#- name: SpacyNLP
#  model: "en_core_web_md"    # Use the medium-sized English model
#- name: SpacyTokenizer
#- name: SpacyFeaturizer
#- name: RegexFeaturizer
#- name: DIETClassifier
#  epochs: 400
#  constrain_similarities: True  # Add this line
#- name: EntitySynonymMapper
#
#policies:
#- name: MemoizationPolicy
#- name: TEDPolicy
#  epochs: 150
#  max_history: 5
#- name: RulePolicy
#  core_fallback_action_name: "action_default_fallback"
#  core_fallback_threshold: 0.7
#  enable_fallback_prediction: true
#assistant_id: 20240729-084527-adagio-quay
