version: '3.1'

services:
  RasaxDocker:
    container_name: RasaxDocker
    image: rasa/rasa:3.6.20-full
    volumes:
      - ./models:/app/models
      - ./RasaXDocker:/app
      - ./:/app
    command: ["run", "--cors", "*", "--enable-api", "--debug", "--model", "models/20240502-172537-maroon-differential.tar.gz"]
    restart: always
    ports:
      - "5005:5005"
    networks:
      - rasax_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 1m

  actions:
    container_name: RasaxDocker_actions
    build: .
    command: ["run", "actions", "--auto-reload"]
    restart: always
    ports:
      - "5055:5055"
    volumes:
      - ./:/app
    networks:
      - rasax_network
    healthcheck:
      test: ["CMD-SHELL", "curl -X POST http://localhost:5055/webhook -H \"Content-Type: application/json\" -d @/app/tests/payload.json"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 1m

  train:
    container_name: rasa_train
    image: rasa/rasa:3.6.20-full
    volumes:
      - ./models:/app/models
      - ./:/app
    command: ["train"]
    networks:
      - rasax_network

  test:
    container_name: rasa_test
    image: rasa/rasa:3.6.20-full
    volumes:
      - ./models:/app/models
      - ./:/app
    command: ["test"]
    networks:
      - rasax_network

networks:
  rasax_network:
    driver: bridge

